// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';


var NavigationState = /* module */[];

var NavigationActions = /* module */[];

var NavigationContainer = /* module */[];

var Navigation = /* module */[];

var Config = /* module */[];

var StackNavigator = /* module */[/* Config */Config];

var ContentComponent = /* module */[];

var ContentOptions = /* module */[];

var Config$1 = /* module */[/* ContentOptions */ContentOptions];

var DrawerNavigator = /* module */[
  /* ContentComponent */ContentComponent,
  /* Config */Config$1
];

var TabBarOptions = /* module */[];

var Config$2 = /* module */[];

var TabNavigator = /* module */[
  /* TabBarOptions */TabBarOptions,
  /* Config */Config$2
];

var NavigationOptions = /* module */[];

var NavigationParams = /* module */[];

var AppContainer = /* module */[];

exports.NavigationState = NavigationState;
exports.NavigationActions = NavigationActions;
exports.NavigationContainer = NavigationContainer;
exports.Navigation = Navigation;
exports.StackNavigator = StackNavigator;
exports.DrawerNavigator = DrawerNavigator;
exports.TabNavigator = TabNavigator;
exports.NavigationOptions = NavigationOptions;
exports.NavigationParams = NavigationParams;
exports.AppContainer = AppContainer;
/* No side effect */
